# Generated by Django 4.2.5 on 2023-09-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='count',
            field=models.IntegerField(default=0, verbose_name='количесво игр'),
        ),
    ]
